### ISSUE TITLE
Занятия 1 и 2.

### ISSUE THREAD

**Issue by stsdmchv** [Elizabeth084/python#1]
Отсутствует строка кодировки.

На будущее: сохраняйте пожалуйста скриншоты через Paint как отдельный файл. Так их можно просмотреть через GitHub и не нужно ничего скачивать на компьютер. Спасибо!

**Comment by Elizabeth084** [comment]
Здравствуйте! Я добавила строку кодировки в программы.

  
>Понедельник, 4 октября 2021, 12:16 +03:00 от Stanislav Demichev ***@***.***>:
> 
> 
>Отсутствует строка кодировки.
>На будущее: с
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Елизавета Башкирова
